-- Insert demo user directly into auth.users table
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_token,
  email_change_token_new,
  email_change,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current_deadline,
  email_change_token_new_deadline,
  is_anonymous
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'admin@dantam.com',
  crypt('admin123', gen_salt('bf')),
  now(),
  now(),
  '',
  '',
  '',
  '',
  '',
  0,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"first_name": "Admin", "last_name": "User", "role": "admin"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  null,
  null,
  false
);

-- Also insert into auth.identities table
INSERT INTO auth.identities (
  provider_id,
  user_id,
  identity_data,
  provider,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES (
  'admin@dantam.com',
  (SELECT id FROM auth.users WHERE email = 'admin@dantam.com'),
  '{"sub": "admin@dantam.com", "email": "admin@dantam.com", "email_verified": true, "phone_verified": false}',
  'email',
  now(),
  now(),
  now()
);